In [1]:
with open('input.txt', 'r') as f:
    vals = np.array(f.readlines()).astype(int)

num = len(vals)
num

200

# Part 1

In [2]:
ix, iy = np.mgrid[:num, :num].reshape(2, num**2)

In [3]:
mask = (vals[ix] + vals[iy]) == 2020
mask.sum()

2

In [4]:
ix[mask], iy[mask]

(array([127, 143]), array([143, 127]))

In [5]:
solution = vals[[ix[mask][0], iy[mask][0]]]
solution

array([1412,  608])

In [6]:
assert solution.sum() == 2020

In [7]:
solution.prod()

858496

# Part 2

In [8]:
ix, iy, iz = np.mgrid[:num, :num, :num].reshape(3, num**3)

In [9]:
mask = (vals[ix] + vals[iy] + vals[iz]) == 2020
mask.sum()

6

In [10]:
ix[mask], iy[mask], iz[mask]

(array([104, 104, 129, 129, 167, 167]),
 array([129, 167, 104, 167, 104, 129]),
 array([167, 129, 167, 104, 129, 104]))

In [11]:
solution = vals[[ix[mask][0], iy[mask][0], iz[mask][0]]]
solution

array([405, 833, 782])

In [12]:
assert solution.sum() == 2020

In [13]:
solution.prod()

263819430